language: R
cache: packages
sudo: false

latex: false
pandoc: false

r_packages:
  - networkDynamicData

warnings_are_errors: true

script:
  - bash test.sh

notifications:
   email:
     on_success: never
     on_failure: change
