language: R
cache: packages
sudo: false

latex: false
pandoc: false

r_packages:
  - networkDynamicData
  - dplyr
  - EpiModel

warnings_are_errors: true

script:
  - bash test.sh

notifications:
  email: false
  slack: epimodel:iY6F3MeHlZ2LCM4MwuVRJj7D
